#!/usr/bin/env python3
"""mkverify.py -- build the Tiny-C Verify pack:

  verify/TCVERIFY.SCRIPT   a Verify P-System keyboard script (the format of
                           PSystemVerify.h: WAIT / TYPE)
  verify/TCVERIFY.zip      TCVERIFY.BLK, the volume the script runs on as
                           unit #5 (compiler, library, headers, tests, the
                           compiler's own sources, CMPCODE)

The script, on the P-System itself:
  1. compiles every test program with CC and runs it; every line of its
     expected output (tests/NAME.expect) must appear, in order
  2. compiles the compiler's 14 modules with CC, links them to
     CC2.CODE and checks (with CMPCODE, a Tiny-C program) that it is
     identical to CC.CODE
  3. compiles and runs a test with CC2
A step whose text never appears stops the run at the next prompt.
"""
import os, sys, zipfile
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import ucsdvol
from tcrun import build_lib, compile_c, INC
from buildtc import build, MODULES

VDIR = os.path.join(ROOT, 'verify')
TESTS = os.path.join(ROOT, 'tests')


def q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '\\r') + '"'


def tests():
    return sorted(f[:-2] for f in os.listdir(TESTS) if f.endswith('.c'))


def run_program(lines, name, expect, keys=''):
    lines += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE %s' % q(name + '\r')]
    if keys:
        lines.append('TYPE %s' % q(keys))
    for l in expect.split('\n'):
        if l.strip():
            lines.append('WAIT %s' % q(l.rstrip()))
    lines.append('WAIT "Command:"')


def compile_step(lines, compiler, what):
    lines += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE %s' % q(compiler + '\r'),
              'WAIT "Compile what file?"', 'TYPE %s' % q(what + '\r'), 'WAIT "Done."', 'WAIT "Command:"']


def remove(lines, names):
    lines += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE "RMFILES\\r"']
    for n in names:
        lines += ['WAIT "Remove?"', 'TYPE %s' % q(n + '\r')]
    lines += ['WAIT "Remove?"', 'TYPE "\\r"', 'WAIT "REMOVED %d"' % len(names), 'WAIT "Command:"']


def script():
    L = ['# Tiny-C Verify: TCVERIFY.BLK on unit #5 (generated by tools/mkverify.py)',
         'WAIT "Command:"', 'TYPE "F"', 'WAIT "Filer:"', 'TYPE "P"', 'WAIT "Prefix"',
         'TYPE "#5:\\r"', 'WAIT "Filer:"', 'TYPE "Q"', 'WAIT "Command:"']
    for t in tests():
        name = t.upper()[:10]
        keys_path = os.path.join(TESTS, t + '.keys')
        keys = open(keys_path, newline='').read() if os.path.exists(keys_path) else ''
        L.append('# ---- test %s' % name)
        compile_step(L, 'CC', '/Z ' + name)      # /Z: the pack runs in Z80 mode too
        # NAME.wait: the texts to wait for instead of NAME.expect (for output
        # with cursor addressing, whose raw bytes the transcript shows differently)
        wait = os.path.join(TESTS, t + '.wait')
        expect = open(wait if os.path.exists(wait) else os.path.join(TESTS, t + '.expect')).read()
        run_program(L, name, expect, keys)
        remove(L, [name + '.OBJ', name + '.CODE'])     # the directory holds 77 files
    L.append('# ---- the compiler compiles itself')
    for m in MODULES:
        compile_step(L, 'CC', '/C ' + m.upper())
    compile_step(L, 'CC', '/L CC2=' + ','.join(m.upper() for m in MODULES))
    L += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE "CMPCODE\\r"',
          'WAIT "First file?"', 'TYPE "CC.CODE\\r"', 'WAIT "Second file?"', 'TYPE "CC2.CODE\\r"',
          'WAIT "IDENTICAL"', 'WAIT "Command:"']
    L.append('# ---- and the compiler it built works')
    compile_step(L, 'CC2', '/Z HANOI')
    run_program(L, 'HANOI', open(os.path.join(TESTS, 'hanoi.expect')).read())
    return '\n'.join(L) + '\n'


def volume(path):
    ucsdvol.main(['new', path, 'TINYCV', '4000'])
    v = ucsdvol.Volume(path)
    code, log = build()
    v.write('CC.CODE', open(code, 'rb').read(), 2)
    v.write('TCLIB.OBJ', open(build_lib(True), 'rb').read(), 5)   # -z: works in Z80 mode too
    v.write('TCMSGS.TEXT', ucsdvol.text_to_ucsd(open(os.path.join(INC, 'tcmsgs.txt')).read()), 3)
    for f in sorted(os.listdir(INC)):
        if f.endswith('.h'):
            v.write(f.upper(), ucsdvol.text_to_ucsd(open(os.path.join(INC, f)).read()), 3)
    for t in tests():
        v.write(t.upper()[:8] + '.C', ucsdvol.text_to_ucsd(open(os.path.join(TESTS, t + '.c')).read()), 3)
    src = os.path.join(ROOT, 'tinyc')
    for m in MODULES:
        v.write(m.upper() + '.C', ucsdvol.text_to_ucsd(open(os.path.join(src, m + '.c')).read()), 3)
    for h in ('tc.h', 'parse.h', 'gen.h'):
        v.write(h.upper(), ucsdvol.text_to_ucsd(open(os.path.join(src, h)).read()), 3)
    tmp = os.path.join(ROOT, 'build', 'verify_tmp')
    os.makedirs(tmp, exist_ok=True)
    for prog in ('cmpcode', 'rmfiles'):
        base, cmp = compile_c(os.path.join(VDIR, prog + '.c'), tmp, z80=True)
        v.write(base + '.CODE', open(cmp, 'rb').read(), 2)
        for ext in ('.i', '.ir', '.obj'):              # compile_c's temporaries
            p = os.path.join(VDIR, prog + ext)
            if os.path.exists(p):
                os.remove(p)
    v.save()


def main():
    blk = os.path.join(ROOT, 'build', 'TCVERIFY.BLK')
    volume(blk)
    open(os.path.join(VDIR, 'TCVERIFY.SCRIPT'), 'w').write(script())
    with zipfile.ZipFile(os.path.join(VDIR, 'TCVERIFY.zip'), 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.write(blk, 'TCVERIFY.BLK')
    print('wrote verify/TCVERIFY.SCRIPT and verify/TCVERIFY.zip')


if __name__ == '__main__':
    main()
