#!/usr/bin/env python3
"""mkverify.py -- build the Tiny-C Verify content, on two volumes (volumes/*.zip)
that go with the system's own: TCVERIF: (VERIFY.SCRIPT, RMFILES) and TCEXPCT:
(NAME.EXPECT, what every test prints), and verify/TCVERIFY.SCRIPT.  Old pack text:

  verify/TCVERIFY.SCRIPT   a Verify P-System keyboard script (the format of
                           PSystemVerify.h: WAIT / TYPE)
  verify/TCVERIFY.zip      TCVERIFY.BLK, the volume the script runs on as
                           unit #5 (compiler, library, headers, tests, the
                           compiler's own sources, CMPCODE)

The script, on the P-System itself:
  1. compiles every test program with CC and runs it; every line of its
     expected output (tests/NAME.expect) must appear, in order
  2. compiles the compiler's 14 modules with CC, links them to
     CC2.CODE and checks (with CMPCODE, a Tiny-C program) that it is
     identical to CC.CODE
  3. compiles and runs a test with CC2
A step whose text never appears stops the run at the next prompt.
"""
import os, sys, zipfile
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import ucsdvol
from tcrun import build_lib, compile_c, INC
from buildtc import build, MODULES
from mkvolume import DEMOS, Vol

VDIR = os.path.join(ROOT, 'verify')
TESTS = os.path.join(ROOT, 'tests')


def q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\r', '\\r') + '"'


def tests():
    return sorted(f[:-2] for f in os.listdir(TESTS) if f.endswith('.c'))


def run_program(lines, name, expect, keys=''):
    lines += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE %s' % q(name + '\r')]
    if keys:
        lines.append('TYPE %s' % q(keys))
    for l in expect.split('\n'):
        if l.strip():
            lines.append('WAIT %s' % q(l.rstrip()))
    lines.append('WAIT "Command:"')


def compile_step(lines, compiler, what):
    lines += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE %s' % q(compiler + '\r'),
              'WAIT "Compile what file?"', 'TYPE %s' % q(what + '\r'), 'WAIT "Done."', 'WAIT "Command:"']


def remove(lines, names):
    lines += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE "TCVERIF:RMFILES\\r"']
    for n in names:
        lines += ['WAIT "Remove?"', 'TYPE %s' % q(n + '\r')]
    lines += ['WAIT "Remove?"', 'TYPE "\\r"', 'WAIT "REMOVED %d"' % len(names), 'WAIT "Command:"']


def where(t):
    """the volume a test program is on (mkvolume.py)"""
    return 'TCEXTRA' if t in DEMOS else 'TCTESTS'


def prefix(v):
    return ['TYPE "F"', 'WAIT "Filer:"', 'TYPE "P"', 'WAIT "Prefix"', 'TYPE "%s:\\r"' % v,
            'WAIT "Filer:"', 'TYPE "Q"', 'WAIT "Command:"']


def script():
    """Units: #5 TINY-C:, #9 TCSRC:, #10 TCTESTS:, #11 TCEXTRA:, #12 TCVERIF:,
    #13 TCEXPCT: -- the system's own volumes, nothing copied: the tests compile
    where their sources are, the compiler rebuilds itself on TCSRC: and TINY-C:."""
    L = ['# Tiny-C Verify (generated by tools/mkverify.py; TCVERIF:VERIFY.SCRIPT)',
         '# units: #5 TINY-C:  #9 TCSRC:  #10 TCTESTS:  #11 TCEXTRA:  #12 TCVERIF:  #13 TCEXPCT:',
         'WAIT "Command:"']
    for t in tests():
        name = t.upper()[:10]
        vol = where(t)
        keys_path = os.path.join(TESTS, t + '.keys')
        keys = open(keys_path, newline='').read() if os.path.exists(keys_path) else ''
        L.append('# ---- test %s (expected output: TCEXPCT:%s.EXPECT)' % (name, name))
        L += prefix(vol)
        compile_step(L, 'TINY-C:CC', '/Z ' + name)      # /Z: runs in Z80 mode too
        # NAME.wait: the texts to wait for instead of NAME.expect (for output
        # with cursor addressing, whose raw bytes the transcript shows differently)
        wait = os.path.join(TESTS, t + '.wait')
        expect = open(wait if os.path.exists(wait) else os.path.join(TESTS, t + '.expect')).read()
        run_program(L, vol + ':' + name, expect, keys)
        remove(L, [name + '.OBJ'])                       # a directory holds 77 files
    L.append('# ---- the compiler compiles itself (TCSRC:BUILD -> TINY-C:CC2.CODE)')
    L += prefix('TCSRC')
    compile_step(L, 'TINY-C:CC', '@BUILD')
    L += ['TYPE "X"', 'WAIT "Execute what file?"', 'TYPE "TCEXTRA:CMPCODE\\r"',
          'WAIT "First file?"', 'TYPE "TINY-C:CC.CODE\\r"', 'WAIT "Second file?"', 'TYPE "TINY-C:CC2.CODE\\r"',
          'WAIT "IDENTICAL"', 'WAIT "Command:"']
    L.append('# ---- and the compiler it built works')
    L += prefix('TCEXTRA')
    compile_step(L, 'TINY-C:CC2', '/Z HANOI')
    run_program(L, 'TCEXTRA:HANOI', open(os.path.join(TESTS, 'hanoi.expect')).read())
    return '\n'.join(L) + '\n'


README_V = """TINY-C VERIFY                                    volume TCVERIF:

Checks Tiny-C on the P-System itself with the system's own volumes, nothing
copied.  Mount: #5 TINY-C:, #9 TCSRC:, #10 TCTESTS:, #11 TCEXTRA:,
#12 TCVERIF: (this), #13 TCEXPCT: (what every test prints).

VERIFY.SCRIPT   a Verify P-System keyboard script (WAIT / TYPE): for every
                test set the prefix to its volume, compile it (X TINY-C:CC,
                /Z NAME), run it, wait for each line of TCEXPCT:NAME.EXPECT
                in order, remove NAME.OBJ (RMFILES; a directory holds 77
                files); then @BUILD on TCSRC:, CMPCODE: TINY-C:CC2.CODE is
                IDENTICAL to CC.CODE, and CC2 compiles and runs HANOI.
RMFILES.CODE    removes the files named, one per line (RMFILES.C)
The results stay on the volumes (TINY-C:CC2.CODE, the objects on TCSRC:,
NAME.CODE on TCTESTS: and TCEXTRA:); the host keeps the volume files.

FILES.TEXT lists every file on this volume.
"""

README_E = """TINY-C EXPECTED OUTPUT                           volume TCEXPCT:

NAME.EXPECT is what test NAME (on TCTESTS: or TCEXTRA:) prints; the Verify
script on TCVERIF: waits for each of its lines, in order.  (Tests with
cursor addressing wait for the texts of tests/NAME.wait instead, and the keys
a test is given are in the script.)

FILES.TEXT lists every file on this volume.
"""


def main():
    sc = script()
    v = Vol('TCVERIF', 4000)
    v.text('README.TEXT', README_V, 'what is on this volume')
    v.text('VERIFY.SCRIPT', sc, 'the Tiny-C Verify script')
    tmp = os.path.join(ROOT, 'build', 'verify_tmp')
    os.makedirs(tmp, exist_ok=True)
    base, code = compile_c(os.path.join(VDIR, 'rmfiles.c'), tmp, z80=True)
    for ext in ('.i', '.ir', '.obj'):
        p = os.path.join(VDIR, 'rmfiles' + ext)
        if os.path.exists(p):
            os.remove(p)
    v.textfile('RMFILES.C', os.path.join(VDIR, 'rmfiles.c'), 'removes the files named, one per line')
    v.binary('RMFILES.CODE', open(code, 'rb').read(), '  (ready to run)')
    v.finish()
    e = Vol('TCEXPCT', 4000)
    e.text('README.TEXT', README_E, 'what is on this volume')
    for t in tests():
        e.textfile(t.upper()[:10] + '.EXPECT', os.path.join(TESTS, t + '.expect'), 'what %s prints' % t)
    e.finish()
    open(os.path.join(VDIR, 'TCVERIFY.SCRIPT'), 'w').write(sc)


if __name__ == '__main__':
    main()
